name: gerador_senhas_autodeploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Use a versão mais recente da ação checkout

    - name: Set up Docker Compose
      run: |
        sudo apt-get -yqq install docker-compose
        docker-compose --version

    - name: Install Node.js and npm
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install HTMLHint
      run: |
        npm install -g htmlhint

    - name: Run HTML tests
      run: |
        # Substitua pelo caminho correto do seu arquivo HTML.
        htmlhint /home/servidor/password_generator/index.html

    - name: SSH into VM and run Docker Compose
      uses: appleboy/ssh-action@master
      with:
        host: 192.168.60.52
        username: root
        key: ${{ secrets.TESTE }}
        port: 22
        script: |
          cd /home/servidor/password_generator/
          docker-compose up --detach
