name: Deploy to Server

on:
  push:
    branches:
      - main  # altere para o nome da sua branch principal, se necessário

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install Dependencies
      run: npm install  # ou o comando necessário para instalar as dependências do seu projeto

    - name: Build
      run: npm run build  # ou o comando necessário para construir o seu projeto

    - name: Verify HTML
      run: |
        cd /home/password_generator/
        # Adicione aqui o comando para verificar o arquivo HTML, por exemplo:
        npx html-validate index.html
        # Certifique-se de instalar as ferramentas necessárias antes de executar este comando

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2
      with:
        server: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        local: "/home/password_generator/"  # substitua com o diretório do seu build
        remote: "/home/password_generator/"  # substitua com o caminho no servidor onde você deseja implantar

    - name: Docker Compose Up
      run: |
        cd /home/password_generator/
        docker-compose up -d
