on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: SSH into Server and Update Repository
      uses: appleboy/ssh-action@master # Versão mais recente da ação ssh-action
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        password: ${{ secrets.SSH_PASSWORD_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: whoami