name: Deploy to Server

on:
 push:
    branches:
      - main

jobs:
 deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2.5.0 # Versão mais recente compatível com Node.js 16

    - name: Set up Node.js
      uses: actions/setup-node@v4 # Versão mais recente da ação setup-node

    - name: Set up Docker Compose
      run: |
        sudo docker-compose -f docker-compose.yml down
        sudo docker-compose -f docker-compose.yml up -d

    - name: SSH into Server and Update Repository
      uses: appleboy/ssh-action@master # Versão mais recente da ação ssh-action
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        script: |
          cd /home/password_generator/
          git pull origin main