name: gerador_senhas_autodeploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        sudo apt-get -yqq install docker-compose
        docker-compose --version

    - name: Install Node.js and npm
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install HTMLHint
      run: |
        npm install -g htmlhint

    - name: Run HTML tests
      run: |
        # Substitua 'home/password_generator/index.html' pelo caminho dos seus arquivos HTML.
        htmlhint home/password_generator/index.html

    - name: SSH into VM and run Docker Compose
      uses: appleboy/ssh-action@master
      with:
        host: 192.168.60.52 
        username: root
        key: SHA256:/gY/IQwqgqenVEr/1OPLnlfgELyIRy268c+4GY61jhQ
        port: 22 
        script: |
          cd /caminho/do/seu/projeto
          docker-compose up --detach
