name: Deploy to Apache

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Apache
        run: |
          # Substitua 'public' pelo diretório onde estão seus arquivos web
          rsync -avz --delete https://github.com/kelviinr/password_generator.git/ servidor@192.168.60.107:/path/to/apache/root
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
